### ISSUE TITLE
Can I use this with redis-mock?

### ISSUE THREAD

**Issue by zardilior** [socketio/socket.io-redis-adapter#308]
I want to run server tests so I am changing the dbs to mocks. So, is this library compatible in some way with an alternate redis client?

**Comment by darrachequesne** [comment]
For future readers:

Yes, alternate Redis clients that implements the same API as the classic [redis](https://github.com/NodeRedis/node-redis) package are supported (like ioredis).

The following methods are used:

- `client.publish(channel, data)` (with data being either a string or a buffer)
- `client.psubscribe(regex)`
- `client.subscribe(channels)`
- `pmessageBuffer` event (for buffers)
- `messageBuffer` event (for strings)

[redis-mock](https://github.com/yeahoffline/redis-mock) does not seem compatible as of today:
- no binary support due to [this line](https://github.com/yeahoffline/redis-mock/blob/a01695359e727f01fc5cf22a697468e6fe55fa12/lib/pubsub.js#L125)
- no "pmessageBuffer" event, only "pmessage" ([here](https://github.com/yeahoffline/redis-mock/blob/a01695359e727f01fc5cf22a697468e6fe55fa12/lib/redis-mock.js#L125-L139))

Nothing that cannot be fixed though :angel:

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
