### ISSUE TITLE
Replacing customHook/customRequest in ^6.0.0

### ISSUE THREAD

**Issue by helderjbe** [socketio/socket.io-redis-adapter#370]
According to the release notes for v6.0.0 in https://socket.io/blog/socket-io-redis-adapter-6-release/:

`customHook and customRequest methods were removed
Those methods will be replaced by a more intuitive API in a future iteration.`

It would be nice to provide an alternative for the devs who were already using customHook and customRequest.

Also, it says that this will be available in a future version. When would that be? Why not simply leave the previous implementation on, as it was already working well?

Great work guys, just wondering about this since I have customHooks implemented in an existing project and would like to upgrade socket io.

**Comment by gchokhonelidze** [comment]
You have to write something like this:
```
	sub.subscribe("MSG");
	nsp.adapter.customRequest = function ({ sender, event, data }) {
		pub.publish("MSG", JSON.stringify({ sender, event, data }));
	};
	sub.on("message", function (channel, message) {
		if (channel !== "MSG") return;
		try {
			const packet = JSON.parse(message);
			//your hook middleware...
		} catch (err) {
			err && err.message && console.log(err.message);
		}
	});
	sub.subscribe("MSG");
```

**Comment by rainy-me** [comment]
Hi! Is there an update on this? Since many pervious issues recommended to use customHook/customRequest to solve common problems like https://github.com/socketio/socket.io-redis/issues/283#issuecomment-437034696, the removal of these functions is blocking me upgrading to socket.io v3, should I consider https://github.com/socketio/socket.io-redis/issues/370#issuecomment-760141541 as the official workaround for now? I'm also curious about when would the future release with a replacement api happen?

**Comment by darrachequesne** [comment]
We have added some utility methods in Socket.IO v4 (the major bump is due to a minor breaking change and should not impact most users).

Documentation: https://socket.io/docs/v3/migrating-from-3-x-to-4-0/#Additional-utility-methods

Starting with `socket.io-redis@6.1.0`, those methods (`fetchSockets`, `socketsJoin`, `socketsLeave` and `disconnectSockets`) now work with multiple Socket.IO servers.

Does it cover all your use cases?

An user suggested to create another flag, [`loopback`](https://github.com/socketio/socket.io/pull/3235#issuecomment-790404193), for inter-server communication. What is your opinion?

**Comment by rainy-me** [comment]
@darrachequesne Thank you for the response! The customHook and customRequest methods were more flexible and allowed me perform some extra logic like gathering server status on every node along with node id. The suggested `loopback` flag seems can be a `customHook/customRequest` replacement, but as you mentioned there's no way to distinguish between client and server messages.

In general, I want know when handling communications happen only between servers (rpc calls), should I rely on socket.io-redis, or should I add a different redis based rpc layer?

**Comment by darrachequesne** [comment]
@rainy-me there is currently no official way to handle communication between servers, but we could indeed add one. I'm open to suggestions on this :pray:

**Comment by rainy-me** [comment]
@darrachequesne I mean it was partially doable just via customHook and customRequest, but since they are removed I have to find a alternative. It'll be really helpful to have it in `socket.io-redis` because we already assign every server node an id and have a mechanism to do communications. Feels redundant to add another rpc layer and may have troubles to associate it to `socket.io-redis` provided node id. However, I'm also totally fine if it won't be implemented because I don't know if other people are interested. Maybe it's just because my use case is rare.

**Comment by martinj** [comment]
I also do some custom things using `customHook` and `customRequest` which currently are blocking me from upgrading `socket.io`

**Comment by hmoush95** [comment]
Same here. I'm blocked from upgrading socket.io past v2 because of this removal. customRequest and customHook allowed us to have inter-node communication (i.e. node 1 telling node 2 to do something). The new methods fetchSockets, socketsJoin, socketsLeave and disconnectSockets) unfortunately do not cover all my use-cases.

**Comment by rainy-me** [comment]
Seems `serverSideEmit` has been implemented and released! Have not try it yet but thank you a lot! @darrachequesne

**Comment by hmoush95** [comment]
Didn't update the thread. But yes, I was able to upgrade socket.io and use serverSideEmit as a replacement for customeRequest. Works like a charm and has been out in production since last week. Thanks a lot!

**Comment by darrachequesne** [comment]
@hmoush95 thanks for the update! :+1: 

Syntax of the `serverSideEmit` method, which was added in `socket.io@4.1.0`:

```js
io.serverSideEmit("hello", "world");

// on the other nodes
io.on("hello", (arg1) => {
  console.log(arg1); // prints "world"
});
```

Let's close this now.
