### ISSUE TITLE
question

### ISSUE THREAD

**Issue by hatemragab** [socketio/socket.io-redis-adapter#440]
Iam new with scale with socket io 
After read I can't understand how the entire emit happened 
First lets say i have on server with 4 cpu 
Then i will run 4 node js instance 
My system use socket io namespace and rooms fro group chat 
Actually i have single chat and group chat
What u can't understand is 
- If one user connect to instance 1
- another connect to instance 2 until finsh 4 instance
- what if user 1 which connect to instance 1 need to join private room with user 2 which in another instance
1. So how can i pass emit to this joined room in specific namespace 
2. Do i need to use socket emitter package ? Note i want to use this in only one server with 4 cpu 
3. How can i know or how can i Force socket to join instance 1 or othere ? To insure scale works good on mutil process 
4. Is socket io adapter store all socket connection on redis memory or on each instance memory ? 
> Thank you

**Comment by derikb** [comment]
I think I can answer these....

1. Once the adaptor is setup, the regular `emit` method will send to all instances.
2. No. The emitter package is only for use outside of your socket.io app (like if you want to send in messages from another app).
3. I think your best bet for that is load balancing your 4 instances so connections get divided up. That's not really specific to the adaptor. In my case we have an AWS load balancer in front of our instances. (Though you do want your load balancer to be sticky so your connections don't get bounced around between instances).
4. The adaptor is not storing anything in redis, it is only using it for the pubsub functionality. (That's why you have to instantiate a pub and a sub redis client.

**Comment by hatemragab** [comment]
Thanks
