### ISSUE TITLE
Property 'allRooms' does not exist on type 'Adapter'.ts(2339)

### ISSUE THREAD

**Issue by alkalox** [socketio/socket.io-redis-adapter#444]
Using[ this snippet from the README](https://github.com/socketio/socket.io-redis-adapter#redisadapterallrooms),

`const rooms = await io.of('/').adapter.allRooms();`

Got a typescript error that allRooms does not exist on adapter ^^
Please update with what works to get the list of all rooms, across multiple nodes.

Using the version `"@socket.io/redis-adapter": "^7.1.0", "socket.io": "^4.4.1",`

**Comment by kilometers** [comment]
+1 -- I'm getting this too.

Related unexpected Typescript behavior is the .rooms.get method returns a generic Set type without any client/password properties.

I'm hoping this is a Typescript issue and nothing to do with the Redis Adapter. Perhaps there's a typescript package needed?

**Comment by LucidThought** [comment]
+1 - I see this as well. I need to reconnect all rooms to the Redis adapter after error in the redis client connections, so this definition would be greatly helpful

**Comment by andrewda** [comment]
Although type assertions aren't ideal, something like this should work for now and is better than `// @ts-ignore` everywhere.

```ts
import { RedisAdapter } from '@socket.io/redis-adapter';

// ...

const rooms = await (io.of('/').adapter as RedisAdapter).allRooms();
```

The issue stems from `socket.io` using the `Adapter` type, which specific adapters then extend with their own implementations. Since there's no feedback about these new types to the `socket.io` module at build time, it has no knowledge that new types should be used. I haven't done enough digging to see if there's an issue open on the main repository about this, but one solution would be to add a `getAdapter` function like so:

```ts
getAdapter<T extends Adapter>(): T {
  return this.adapter as T;
}
```

Then, you would be able to call:

```ts
const rooms = await io.of('/').getAdapter<RedisAdapter>().allRooms();
```

I'm no TypeScript genie, so someone might have a better, more elegant solution to this problem!

**Comment by darrachequesne** [comment]
You are right, the `allRooms()` method is deliberately not exposed, as it returns every rooms in the cluster, even private ones (the ones linked to each connection, based on the Socket#id attribute). The `allRooms()` method is specific to this adapter, and might be removed in the next major release.

You can use the `serverSideEmit()` method instead:

```js
const fetchPublicRooms = (namespace) => {
  const rooms = [];

  namespace.adapter.rooms.forEach((sockets, room) => {
    const isPrivate = sockets.size === 1 && sockets.has(room);
    if (!isPrivate) {
      rooms.push(room);
    }
  });

  return rooms;
}

// requester
const allRooms = fetchPublicRooms(io.of("/"));

io.timeout(5000).serverSideEmit("all-rooms", (err, responses) => {
  if (err) {
    // something went wrong
  }
  responses.forEach(rooms => {
    Array.prototype.push.apply(allRooms, rooms):
  ));
  console.log(allRooms);
});

// receiver
io.on("all-rooms", (callback) => {
  callback(fetchPublicRooms(io.of("/")));
});
```

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
